### ISSUE TITLE
Build error on macOS 13: missing python2.7

### ISSUE THREAD

**Issue by wenkokke** [dreal/homebrew-dreal#12]
This is an issue installing `robotlocomotion/director/ibex`.

However, since they don't accept issue reports, I figured you may still want to be aware, as it impacts installation of dreal:
```
==> Installing dreal/dreal/dreal dependency: robotlocomotion/director/ibex@2.7.4
==> ./waf configure --prefix=/opt/homebrew/Cellar/ibex@2.7.4/2.7.4_13 --enable-shared --with-optim --with-solver --with-affine-extend
Last 15 lines from /Users/keri/Library/Logs/Homebrew/ibex@2.7.4/01.waf:
2023-04-11 11:34:59 +0000

./waf
configure
--prefix=/opt/homebrew/Cellar/ibex@2.7.4/2.7.4_13
--enable-shared
--with-optim
--with-solver
--with-affine-extended
--interval-lib=filib
--lp-lib=clp
--clp-path=/opt/homebrew/opt/clp

env: python2.7: No such file or directory
```

**Comment by soonhokong** [comment]
@wenkokke , a simple patch like https://github.com/dreal-deps/ibex-lib/commit/352eeeb2345fb2b7a7ec248b44770d8cdc4a5d67 should fix the problem.

**Comment by alpylmz** [comment]
The issue still persists. Brew tries to install 2.7.4_13, which is not patched.
